name: Contrast Security Sarif
on:
  push:
    branches:
      - "main"
jobs:
  Check-Dependency-Vulnerabilities:
    runs-on: ubuntu-latest
    steps:

      - name: Get Contrast SARIF
        uses: Contrast-Security-OSS/contrast-sca-action@v2
        with:
          apiKey: ${{ secrets.CONTRAST__API__API_KEY }}
          apiUrl: https://apptwo.contrastsecurity.com
          applicationId: 56058ef3-ebc6-4691-948d-ddca1124332d #app sessions
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          command: sarif
          #ghasEnabled: false
          #metadata: sessionMetadataKey1=value,key2=value...
          orgId: e06e9701-bf90-49bb-af4c-39f28c4e7cb2
